### ISSUE TITLE
Too restrictive with allowed characters? (Request to support kebab case and other letters)

### ISSUE THREAD

**Issue by MeepTech** [OPD-libs/OPD-libs#23]
https://github.com/OPD-libs/OPD-libs/blob/0bba7c1aa2036c1e7e7fa0db4f4cdcac78aab063/libs/OPD-metadata-lib/src/Utils.ts#L62

When using the property indexer (`object["index"]`) I don't think the string is restricted to only these characters, and since Obsidian is a note-taking app it may be prudent to allow other characters, such as vowels with macrons and kebab-case properties.

As an example, I personally use kebab-case to name almost all of my Yaml properties, and this doesn't seem to support that.

**Comment by mProjectsCode** [comment]
Yes, the parser for that is quite restrictive atm. That is a thing that definitely needs work before an official release

**Comment by mProjectsCode** [comment]
I might ditch the allowed character restriction completely and only validate things like square brackets and quotation marks being closed

**Comment by MeepTech** [comment]
Mhmm, I agree it may be easier in js to only check invalid over valid chars haha, the language is a bit nuts.
I'd also validate things like double period(`.`)s and ?! markers if they aren't supported.
It's a great parser overall though! Better than mine was haha.
